channels:
- conda-forge
dependencies:
- bzip2=1.0.8=h0ad9c76_8
- c-compiler=1.11.0=h528c1b4_0
- ca-certificates=2026.1.4=h4c7d964_0
- clang=19.1.7=default_hac490eb_7
- clang-19=19.1.7=default_hac490eb_7
- compiler-rt=19.1.7=h49e36cd_1
- compiler-rt_win-64=19.1.7=h49e36cd_1
- compilers=1.11.0=h57928b3_0
- cxx-compiler=1.11.0=h1c1089f_0
- cython=3.2.4=py311h9990397_0
- flang=19.1.7=hbeecb71_0
- flang_impl_win-64=19.1.7=h719f0c7_0
- flang_win-64=19.1.7=h719f0c7_0
- fortran-compiler=1.11.0=h95e3450_0
- icu=78.2=h637d24d_0
- libblas=3.11.0=5_hf2e6a31_mkl
- libcblas=3.11.0=5_h2a3cdd5_mkl
- libexpat=2.7.3=hac47afa_0
- libffi=3.5.2=h3d046cb_0
- libflang=19.1.7=he0c23c2_0
- libglib=2.86.3=h0c9aed9_1
- libhwloc=2.12.2=default_h4379cf1_1000
- libiconv=1.18=hc1393d2_2
- libintl=0.22.5=h5728263_3
- liblapack=3.11.0=5_hf9ab0e9_mkl
- libllvm19=19.1.7=h830ff33_2
- liblzma=5.8.2=hfd05255_0
- libsqlite=3.51.2=hf5d6505_0
- libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
- libxml2=2.15.1=h779ef1b_1
- libxml2-16=2.15.1=h3cfd58e_1
- libzlib=1.3.1=h2466b09_2
- lld=21.1.8=hc465015_0
- llvm-openmp=21.1.8=h4fa8253_0
- llvm-tools=19.1.7=h752b59f_2
- mkl=2025.3.0=hac47afa_455
- numpy=2.4.2=py311h80b3fa1_1
- openssl=3.6.1=hf411b9b_1
- packaging=26.0=pyhcf101f3_0
- pcre2=10.47=hd2b5f0e_0
- pip=26.0.1=pyh8b19718_0
- pkg-config=0.29.2=h88c491f_1009
- python=3.11.14=h0159041_3_cpython
- python_abi=3.11=8_cp311
- setuptools=82.0.0=pyh332efcf_0
- tbb=2022.3.0=h3155e25_2
- tk=8.6.13=h6ed50ae_3
- tzdata=2025c=hc9c84f9_1
- ucrt=10.0.26100.0=h57928b3_0
- vc=14.3=h41ae7f8_34
- vc14_runtime=14.44.35208=h818238b_34
- vcomp14=14.44.35208=h818238b_34
- vs2022_win-64=19.44.35207=ha74f236_34
- vswhere=3.1.7=h40126e0_1
- wheel=0.46.3=pyhd8ed1ab_0
- zstd=1.5.7=h534d264_6
- pip:
  - mido==1.3.3
  - scipy==1.17.0
  - git+https://github.com/CPJKU/madmom.git
name: td_madmom_311
prefix: C:\Users\janni\Desktop\td_lastBeatStanding\Miniconda3\envs\td_madmom_311
